include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SAFECleanerPref
SAFECleanerPref_FILES = SAFECleanerRoot.m
SAFECleanerPref_INSTALL_PATH = /var/jb/Library/PreferenceBundles
SAFECleanerPref_FRAMEWORKS = UIKit Preferences
SAFECleanerPref_PRIVATE_FRAMEWORKS = Preferences
SAFECleanerPref_LDFLAGS = -ldl

include $(THEOS_MAKE_PATH)/bundle.mk